### ISSUE TITLE
Subtracting an intersecting shape

### ISSUE THREAD

**Issue by Daubsy** [kaosat-dev/CoffeeSCad#129]
I am a java/coffeescript noob so forgive me if this is a dumb question. I have a positive object that was created from intersecting several shapes. Is is possible to now subtract this object from another object? I cant seem to figure it out...

**Comment by kaosat-dev** [comment]
Hello Daubster:
Yes it is possible : normally you just have to do 
    resultOfIntersection.subtract(otherObject).
If you post some code I can help in more details:)

**Comment by Daubsy** [comment]
Ah, got it. Thanks!
