### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ghost** [kaosat-dev/CoffeeSCad#157]
Does COffeeSCad require anything but a webserver to run? (or does it need node, frameworks, etc)

**Comment by kaosat-dev** [comment]
Hello @berserk82 , sorry but the project is pretty much dead. I think you could just build the 'distributable' file once using node and use any webserver to run, there is nothing fancy in there, but the whole tooling and everything else is very outdated, so not sure any of it still works.
Please try https://openjscad.org/ instead, it is quite similar, and well maintained (I am also working on it)

**Comment by ghost** [comment]
I'm interested in no-node-required apps

**Comment by kaosat-dev** [comment]
@berserk82 for OpenJSCAD (and back then for CoffeeSCAD), Node.js is only needed for some very specific development OF the software itself, you can host your designs running in OpenJSCAD without Node.js or anything else, it is just a simple html/js file

**Comment by ghost** [comment]
Ah, ok, thanks. I'll look at OpenJsCad then.
