### ISSUE TITLE
Cylinder doesn't move?

### ISSUE THREAD

**Issue by FowsCoffeeScad** [kaosat-dev/CoffeeSCad#47]
Hi,

I've been trying this Coffeescad and I start to like it.
But I've notice I can't move a cylinder with the 'center' command
The only thing what I can change is put axis in center of Cylinder and put Cylinder on x,y axis
For a cube and other things the center command works except for this cylinder.
It's a bug or it's me?

**Comment by kaosat-dev** [comment]
Hello, thanks for the feeback !
You are right, I checked, and the center option for Cylinder's does not work.
I will fix it this evening !
