### ISSUE TITLE
Fix cakefile / dev issues

### ISSUE THREAD

**Issue by kaosat-dev** [kaosat-dev/CoffeeSCad#70]
Some people have reported problems with the cakefile's serveWatch task , and also (very likely related) following report when trying to run localy using serveWatch's serve feature (which is meant for dev purposes /experimental only)
Chrome :
undefined disable_require.js:2
Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:8090/app/config.js
Uncaught Error: Script error http://requirejs.org/docs/errors.html#scripterror require.min.js:31

**Comment by derrickoswald** [comment]
I think this is resolved and can be closed.
At least it no longer has the errors mentioned and it's successfully serveWatching.

**Comment by kaosat-dev** [comment]
Agreed, closing this, will reopen if/when needed.
