### ISSUE TITLE
Code Editor too big

### ISSUE THREAD

**Issue by se5a** [kaosat-dev/CoffeeSCad#83]
Code editor as it currently exists is far too big, 
I 'd suggest minimizing white space around the border,
and if possible add autohide to the 'projects' part of it.

**Comment by kaosat-dev** [comment]
This is now implemented :)
Will try to make further improvements in the future. (make it "dockable" to the side etc)

**Comment by ryneches** [comment]
You say the Code Editor is too big? I say the spoon is too big!
![iamabananawd7](https://f.cloud.github.com/assets/440383/319911/77964534-98f6-11e2-94f6-149680ffcbbe.jpg)
