### ISSUE TITLE
aspect ratio of rendered object is relative to browser window. 

### ISSUE THREAD

**Issue by se5a** [kaosat-dev/CoffeeSCad#92]
heh. oops? 
should be an easy fix... 
it also seems to affect the thumbnail weirdly as well.

**Comment by kaosat-dev** [comment]
actually, the way it previously worked was wrong :) The aspect ratio should be kept, no matter the dimensions of the window. (if that is not the way it is behaving for you, can you please post a screenshot here ?) thanks :)
The thumbnails are behaving weirdly though , need to fix that.

**Comment by se5a** [comment]
When you say previously, how long ago? it appears to be working correctly now.

**Comment by kaosat-dev** [comment]
it was friday evening , so around the time you posted:)

**Comment by se5a** [comment]
I guess this one can be marked as fixed then ;)

**Comment by kaosat-dev** [comment]
indeed :)
i will add a new one specifically for the thumbnails (which are generally broken anywayà
