### ISSUE TITLE
Parse error in src/app/config.coffee

### ISSUE THREAD

**Issue by markkimsal** [kaosat-dev/CoffeeSCad#94]
$ cake serveWatch
The "sys" module is now called "util". It should have a similar interface.
Sever starting: at http://127.0.0.1:8090/
In src/app/config.coffee, Parse error on line 74: Unexpected 'TERMINATOR'
In src/app/modules/config.coffee, Parse error on line 76: Unexpected 'TERMINATOR'

/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:246
        throw e;
              ^
Error: watch EMFILE
    at errnoException (fs.js:636:11)
    at FSWatcher.start (fs.js:663:11)
    at Object.watch (fs.js:691:11)
    at /usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:271:20
    at Object.oncomplete (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:132:11)

**Comment by kaosat-dev** [comment]
can you please tell me what system you are having this problem on ?
and what version of coffeescript is installed ?
(try coffee -v)

**Comment by markkimsal** [comment]
Ubuntu 12.04 , kernel 3.3.7

CoffeeScript version 1.6.1

npm list
npm WARN coffee-script@1.6.1 package.json: bugs['name'] should probably be bugs['url']
CoffeeScad@0.2.0 /home/mark/public_html/CoffeeSCad
├─┬ connect@2.7.4 
│ ├── buffer-crc32@0.1.1 
│ ├── bytes@0.2.0 
│ ├── cookie@0.0.5 
│ ├── cookie-signature@0.0.1 
│ ├── debug@0.7.2 
│ ├── formidable@1.0.11 
│ ├── fresh@0.1.0 
│ ├── pause@0.0.1 
│ ├── qs@0.5.1 
│ └─┬ send@0.1.0 
│   ├── mime@1.2.6 
│   └── range-parser@0.0.4 
├─┬ findit@0.1.2 
│ └─┬ seq@0.3.5 
│   ├─┬ chainsaw@0.0.9 
│   │ └── traverse@0.3.9 
│   └─┬ hashish@0.0.4 
│     └── traverse@0.6.3 
├─┬ glob@3.1.21 
│ ├── graceful-fs@1.2.0 
│ ├── inherits@1.0.0 
│ └─┬ minimatch@0.2.11 
│   ├── lru-cache@2.3.0 
│   └── sigmund@1.0.0 
├── mkdirp@0.3.5 
├── node-zip@1.0.1 
├── requirejs@2.1.5 
└─┬ watch-tree-maintained@0.1.2 
  ├── async@0.2.6 
  ├── async_testing@0.3.2 
  ├── coffee-script@1.6.1 
  ├─┬ optimist@0.3.7 
  │ └── wordwrap@0.0.2 
  └── underscore@1.4.4

**Comment by kaosat-dev** [comment]
if you do a pull , it should be fixed:)
(it was due to some weird changes to how comment blocks are handled in object literals.)

**Comment by markkimsal** [comment]
That got rid of the syntax errors, but I still had the Error: watch EMFILE error.

Seems that node.js fs watch libraries need high inotify file counts.  This fixed it:

~/public_html/CoffeeSCad$ cat /proc/sys/fs/inotify/max_user_instances
128
~/public_html/CoffeeSCad$ sudo su -c 'echo 1024 > /proc/sys/fs/inotify/max_user_instances'
~/public_html/CoffeeSCad$ cat /proc/sys/fs/inotify/max_user_instances
1024
