### ISSUE TITLE
display log messages AND errors 

### ISSUE THREAD

**Issue by kaosat-dev** [kaosat-dev/CoffeeSCad#99]
Right now , one clears the others, which is not good

**Comment by se5a** [comment]
is that part of the reason we're not seeing line numbers in errors?

**Comment by kaosat-dev** [comment]
its related but not the cause of :) see issue #100

**Comment by kaosat-dev** [comment]
Tagging this as unresolvable, due to the way compiling works, it is currently not possible to have both logs and errors (logs imply getting a sucessful compile)
